### PR TITLE
add home button on results page.

### PR DESCRIPTION
**Pull request by mahmedov**

### CODE REVIEW

**Comment by eugrdn** [comment]
Is this really necessary to update lock files?

**Comment by mahmedov** [comment]
I am sorry, I was working on a project with a coworker and he asked me to update the lock files and I just automatically did that. I will make a new pull request without the lock file commit.

**Comment by eugrdn** [comment]
But it isn't necessary to close PR, you could only remove last commit :)

**Comment by eugrdn** [comment]
thanks, for the future it would be better if you will name the branches with more descriptive sentence something like `home-button` or `feat/home-button` instead of `dev`. You could check some style guides for this.

**Comment by mahmedov** [comment]
Got it! 👍

**Pull request merged**
